# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jean-Marc Skopek
email: jeanmarc@skopek.ca
description: > # this means to ignore newlines until "baseurl:"
  Just another software developer slowly making his way around the world.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jeanmarc.skopek.ca" # the base hostname & protocol for your site
twitter_username: jmskopek
github_username:  jskopek

permalink: /posts/:categories/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
exclude: ["vendor"]

collections:
    timelapses:
        output: true
    dronepans:
        output: true
